-- DeepSeek V4 Flash 0731 fair-use limiter.
-- KEYS share deepseek:fup:v1:{account_hmac}:* and therefore one Redis hash slot.
-- ARGV[1] action: acquire | heartbeat | release
-- ARGV[2] opaque lease identifier (already generated by the application)
-- ARGV[3..5] HMAC-derived IP, country and UA-family signals
-- ARGV[6] completed flag (1 only for a real normal completion)

local live_key = KEYS[1]
local expiry_key = KEYS[2]
local window_key = KEYS[3]
local total_key = KEYS[4]
local success_key = KEYS[5]
local penalty_key = KEYS[6]
local risk_ip_key = KEYS[7]
local risk_country_key = KEYS[8]
local risk_ua_key = KEYS[9]
local events_key = KEYS[10]

local action = ARGV[1]
local lease_id = ARGV[2]
local risk_ip = ARGV[3]
local risk_country = ARGV[4]
local risk_ua = ARGV[5]
local completed = ARGV[6] == '1'

local PEAK_LIMIT = 10
local DEGRADED_LIMIT = 1
local CONCURRENT_SECONDS_LIMIT = 1800
local SUCCESS_LIMIT = 600
local ADMITTED_LIMIT = 750
local WINDOW_MS = 600000
local STALE_MS = 45000
local STRIKE_WINDOW_MS = 3600000
local DEGRADE_MS = 1800000
local RISK_WINDOW_MS = 86400000

local redis_time = redis.call('TIME')
local now_ms = tonumber(redis_time[1]) * 1000 + math.floor(tonumber(redis_time[2]) / 1000)

local function split_lease(value)
  if not value then
    return nil, nil, nil
  end
  local started, charged, heartbeat = string.match(value, '([^|]+)|([^|]+)|([^|]+)')
  return tonumber(started), tonumber(charged), tonumber(heartbeat)
end

local function expire_all()
  redis.call('EXPIRE', live_key, 7200)
  redis.call('EXPIRE', expiry_key, 7200)
  redis.call('EXPIRE', window_key, 7200)
  redis.call('EXPIRE', total_key, 7200)
  redis.call('EXPIRE', success_key, 7200)
  redis.call('EXPIRE', penalty_key, 7200)
  redis.call('EXPIRE', events_key, 7200)
  redis.call('EXPIRE', risk_ip_key, 172800)
  redis.call('EXPIRE', risk_country_key, 172800)
  redis.call('EXPIRE', risk_ua_key, 172800)
end

local function charge_interval(lease_id, start_ms, end_ms)
  if not start_ms or not end_ms or end_ms <= start_ms then
    return
  end
  local lower_ms = now_ms - WINDOW_MS
  if end_ms <= lower_ms then
    return
  end
  if start_ms < lower_ms then
    start_ms = lower_ms
  end
  local member = start_ms .. '|' .. end_ms .. '|' .. lease_id
  redis.call('ZADD', window_key, end_ms, member)
end

local function charge_lease(id, end_ms)
  local raw = redis.call('HGET', live_key, id)
  if not raw then
    return
  end
  local started_ms, charged_ms, heartbeat_ms = split_lease(raw)
  if not charged_ms then
    charged_ms = started_ms
  end
  if end_ms > charged_ms then
    charge_interval(id, charged_ms, end_ms)
    charged_ms = end_ms
  end
  redis.call('HSET', live_key, id, started_ms .. '|' .. charged_ms .. '|' .. heartbeat_ms)
end

local function prune_stale_leases()
  local stale = redis.call('ZRANGEBYSCORE', expiry_key, '-inf', now_ms)
  for _, id in ipairs(stale) do
    local raw = redis.call('HGET', live_key, id)
    local _, _, heartbeat_ms = split_lease(raw)
    if heartbeat_ms then
      charge_lease(id, math.min(now_ms, heartbeat_ms + STALE_MS))
    end
    redis.call('HDEL', live_key, id)
    redis.call('ZREM', expiry_key, id)
  end
end

local function charge_live_leases()
  local leases = redis.call('HGETALL', live_key)
  for index = 1, #leases, 2 do
    charge_lease(leases[index], now_ms)
  end
end

local function prune_window()
  redis.call('ZREMRANGEBYSCORE', total_key, '-inf', '(' .. (now_ms - WINDOW_MS))
  redis.call('ZREMRANGEBYSCORE', success_key, '-inf', '(' .. (now_ms - WINDOW_MS))
  redis.call('ZREMRANGEBYSCORE', window_key, '-inf', '(' .. (now_ms - WINDOW_MS))
end

local function concurrent_seconds()
  local total = 0
  local lower_ms = now_ms - WINDOW_MS
  local members = redis.call('ZRANGEBYSCORE', window_key, '-inf', now_ms)
  for _, member in ipairs(members) do
    local start_ms, end_ms = string.match(member, '^(%d+)|(%d+)|')
    start_ms = tonumber(start_ms)
    end_ms = tonumber(end_ms)
    if start_ms and end_ms then
      if start_ms < lower_ms then
        start_ms = lower_ms
      end
      if end_ms > now_ms then
        end_ms = now_ms
      end
      if end_ms > start_ms then
        total = total + (end_ms - start_ms) / 1000
      end
    end
  end
  return total
end

local function record_risk()
  if risk_ip ~= '' then
    redis.call('ZADD', risk_ip_key, now_ms, risk_ip)
  end
  redis.call('ZREMRANGEBYSCORE', risk_ip_key, '-inf', '(' .. (now_ms - RISK_WINDOW_MS))
  local ip_count = redis.call('ZCARD', risk_ip_key)

  if risk_country ~= '' then
    redis.call('ZADD', risk_country_key, now_ms, risk_country)
  end
  redis.call('ZREMRANGEBYSCORE', risk_country_key, '-inf', '(' .. (now_ms - RISK_WINDOW_MS))
  local country_count = redis.call('ZCARD', risk_country_key)

  if risk_ua ~= '' then
    redis.call('ZADD', risk_ua_key, now_ms, risk_ua)
  end
  redis.call('ZREMRANGEBYSCORE', risk_ua_key, '-inf', '(' .. (now_ms - RISK_WINDOW_MS))
  if ip_count >= 8 or country_count >= 3 then
    return 1
  end
  return 0
end

local function record_exhaustion(reason)
  local event_id = reason .. ':' .. math.floor(now_ms / WINDOW_MS)
  local inserted = redis.call('ZADD', events_key, 'NX', now_ms, event_id)
  redis.call('ZREMRANGEBYSCORE', events_key, '-inf', '(' .. (now_ms - STRIKE_WINDOW_MS))
  local strike_count = redis.call('ZCARD', events_key)
  local degrade_until = tonumber(redis.call('HGET', penalty_key, 'degrade_until')) or 0
  local last_notified = tonumber(redis.call('HGET', penalty_key, 'last_notified')) or 0
  local notify = 0
  if inserted == 1 and strike_count >= 3 and degrade_until <= now_ms then
    degrade_until = now_ms + DEGRADE_MS
    redis.call('HSET', penalty_key, 'degrade_until', degrade_until)
    if last_notified == 0 or last_notified + STRIKE_WINDOW_MS <= now_ms then
      redis.call('HSET', penalty_key, 'last_notified', now_ms)
      notify = 1
    end
  end
  return strike_count, degrade_until, notify
end

local function result(allowed, reason, notify, risk_marked)
  local degrade_until = tonumber(redis.call('HGET', penalty_key, 'degrade_until')) or 0
  local effective_limit = PEAK_LIMIT
  if degrade_until > now_ms then
    effective_limit = DEGRADED_LIMIT
  end
  local strike_count = redis.call('ZCARD', events_key)
  return {
    allowed and 1 or 0,
    reason or '',
    redis.call('HLEN', live_key),
    concurrent_seconds(),
    redis.call('ZCARD', total_key),
    redis.call('ZCARD', success_key),
    effective_limit,
    math.floor(degrade_until / 1000),
    notify or 0,
    risk_marked or 0,
    strike_count,
  }
end

prune_stale_leases()
charge_live_leases()
prune_window()
local risk_marked = 0

if action == 'acquire' then
  risk_marked = record_risk()
  if redis.call('HEXISTS', live_key, lease_id) == 1 then
    expire_all()
    return result(true, 'already_admitted', 0, risk_marked)
  end

  local degrade_until = tonumber(redis.call('HGET', penalty_key, 'degrade_until')) or 0
  local effective_limit = PEAK_LIMIT
  if degrade_until > now_ms then
    effective_limit = DEGRADED_LIMIT
  end
  if redis.call('HLEN', live_key) >= effective_limit then
    expire_all()
    return result(false, 'concurrency_limit', 0, risk_marked)
  end

  local reason = nil
  if concurrent_seconds() >= CONCURRENT_SECONDS_LIMIT then
    reason = 'concurrent_seconds_limit'
  elseif redis.call('ZCARD', success_key) >= SUCCESS_LIMIT then
    reason = 'success_request_limit'
  elseif redis.call('ZCARD', total_key) >= ADMITTED_LIMIT then
    reason = 'admitted_request_limit'
  end
  if reason then
    local _, _, notify = record_exhaustion(reason)
    expire_all()
    return result(false, reason, notify, risk_marked)
  end

  redis.call('HSET', live_key, lease_id, now_ms .. '|' .. now_ms .. '|' .. now_ms)
  redis.call('ZADD', expiry_key, now_ms + STALE_MS, lease_id)
  redis.call('ZADD', total_key, now_ms, lease_id)
  expire_all()
  return result(true, '', 0, risk_marked)
end

if action == 'heartbeat' then
  if redis.call('HEXISTS', live_key, lease_id) == 0 then
    return result(false, 'lease_not_found', 0, 0)
  end
  charge_lease(lease_id, now_ms)
  if concurrent_seconds() >= CONCURRENT_SECONDS_LIMIT then
    local _, _, notify = record_exhaustion('concurrent_seconds_limit')
    redis.call('HDEL', live_key, lease_id)
    redis.call('ZREM', expiry_key, lease_id)
    expire_all()
    return result(false, 'concurrent_seconds_limit', notify, 0)
  end
  local started_ms, charged_ms, _ = split_lease(redis.call('HGET', live_key, lease_id))
  redis.call('HSET', live_key, lease_id, started_ms .. '|' .. charged_ms .. '|' .. now_ms)
  redis.call('ZADD', expiry_key, now_ms + STALE_MS, lease_id)
  expire_all()
  return result(true, 'heartbeat', 0, 0)
end

if action == 'release' then
  if redis.call('HEXISTS', live_key, lease_id) == 0 then
    return result(true, 'already_released', 0, 0)
  end
  charge_lease(lease_id, now_ms)
  redis.call('HDEL', live_key, lease_id)
  redis.call('ZREM', expiry_key, lease_id)
  if completed then
    redis.call('ZADD', success_key, 'NX', now_ms, lease_id)
  end
  expire_all()
  return result(true, 'released', 0, 0)
end

return result(false, 'invalid_action', 0, 0)
